import {TenderMarket} from './market';
import {Component,signal,computed,OnDestroy} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
@Component({selector:'app-tender-workspace',standalone:true,imports:[CommonModule,FormsModule,TenderMarket],templateUrl:'./tender.html',styleUrl:'./tender.scss'})
export class TenderWorkspace implements OnDestroy{
 marketView=true;
 session=signal<any>(null);items=signal<any[]>([]);selected=signal<any>(null);section=signal('pursuits');tab=signal('overview');busy=signal(false);error=signal('');notice=signal('');modal=signal('');sources=signal<any[]>([]);audit=signal<any>(null);team=signal<any[]>([]);
 search='';country='';stage='';loginForm={name:'',email:'',password:''};form:any={};fields:any[]=[];formTitle='';formAction='';formMethod='POST';response='';resource='companies';live=signal<any>(null);liveError=signal('');liveQuery='';livePage=1;linkKind='supplier';document=signal<any>(null);version=signal<any>(null);includeInBid=false;
 readyCount(){return this.items().filter(t=>t.readiness.ready).length;}
 readonly feedExample=JSON.stringify([{title:'Published contract opportunity',issuer:'Issuing authority',reference:'Official reference',country:'Country name',currency:'USD',deadline:'2027-01-31T12:00:00Z',timezone:'UTC',sourceUrl:'https://procurement.example/tender',description:'Published scope',deliveryDays:120}],null,2);
 readonly stages=['discovered','qualifying','bid_preparation','internal_review','ready','submitted','clarification','shortlisted','negotiation','awarded','lost','no_bid'];
 readonly tabs=['overview','documents','compliance','commercial','delivery','proposal','review','activity'];
 readonly resources=['companies','contacts','deals','quotes','products','knowledge','context','profile','pipelines','workflows'];
 filtered(){return this.items().filter(t=>(!this.country||t.country===this.country)&&(!this.stage||t.stage===this.stage)&&`${t.title} ${t.issuer} ${t.reference}`.toLowerCase().includes(this.search.toLowerCase()));}
 countries=computed(()=>[...new Set(this.items().map(t=>t.country))].sort());
 active=computed(()=>this.items().filter(t=>!['awarded','lost','no_bid'].includes(t.stage)));reviewer=computed(()=>['administrator','reviewer'].includes(this.session()?.user?.role));editor=computed(()=>['administrator','reviewer','contributor'].includes(this.session()?.user?.role));
 private timer=window.setInterval(()=>{if(this.section()==='intelligence'&&!this.busy()&&!this.modal()&&this.session()?.user)void this.loadLive();},60000);
 constructor(){void this.initialize();}ngOnDestroy(){clearInterval(this.timer);}
 headers(){return {'Content-Type':'application/json','X-Workspace-Client':'tender-ui','X-Tender-Session':sessionStorage.getItem('tender-session')||'',...(sessionStorage.getItem('g8-access')?{Authorization:`Bearer ${sessionStorage.getItem('g8-access')}`}:{})};}
 async api(path:string,method='GET',body?:any){const r=await fetch('/api/tender/'+path,{method,headers:this.headers(),body:body===undefined?undefined:JSON.stringify(body)});let data;try{data=await r.json();}catch{throw new Error('Tender backend is unavailable. Restart the application server.');}if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data;}
 async initialize(){this.busy.set(true);this.error.set('');try{this.session.set(await this.api('session'));if(this.session().user)await this.reload();}catch(e){this.error.set(this.message(e));}finally{this.busy.set(false);}}
 async authenticate(){this.busy.set(true);this.error.set('');try{const result=await this.api(this.session()?.needsBootstrap?'bootstrap':'login','POST',this.loginForm);sessionStorage.setItem('tender-session',result.token);this.loginForm.password='';this.session.set(await this.api('session'));await this.reload();}catch(e){this.error.set(this.message(e));}finally{this.busy.set(false);}}
 async logout(){await this.api('logout','POST',{});this.marketView=true;this.error.set('');sessionStorage.removeItem('tender-session');this.selected.set(null);this.items.set([]);await this.initialize();}
 async reload(){if(['issuer','contributor'].includes(this.session()?.user?.role)){this.items.set([]);return;}const result=await this.api('tenders');this.items.set(result.tenders);if(this.selected())this.selected.set(result.tenders.find((t:any)=>t.id===this.selected().id)||null);}
 async refresh(){this.busy.set(true);this.error.set('');try{await this.reload();}catch(e){this.error.set(this.message(e));}finally{this.busy.set(false);}}
 message(e:any){return e?.message||'The request could not be completed.';}
 label(s:string){return s.replace(/_/g,' ');}
 money(n:number,currency=this.selected()?.currency||'USD'){return new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:2}).format(n||0);}
 date(value:string,zone?:string){try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short',timeZone:zone||this.selected()?.timezone||'UTC'}).format(new Date(value));}catch{return value;}}
 days(t:any){return Math.ceil((Date.parse(t.deadline)-Date.now())/86400000);}
 pick(t:any){this.selected.set(t);this.tab.set('overview');this.response=t.response;this.error.set('');}
 async navigate(section:string){this.section.set(section);this.error.set('');try{if(section==='sources')this.sources.set(await this.api('sources'));if(section==='intelligence')await this.loadLive();if(section==='audit')this.audit.set(await this.api('audit'));if(section==='team')this.team.set(await this.api('team'));}catch(e){this.error.set(this.message(e));}}
 async loadLive(page=1){this.busy.set(true);this.liveError.set('');try{this.live.set(await this.api(`live/${this.resource}?page=${page}&q=${encodeURIComponent(this.liveQuery)}`));this.livePage=page;}catch(e){this.live.set(null);this.liveError.set(this.message(e));}finally{this.busy.set(false);}}
 rowName(row:any){return row.name||row.title||row.quote_number||[row.first_name,row.last_name].filter(Boolean).join(' ')||row.id||'Graph8 record';}
 linkOptions(){return this.resource==='companies'?['supplier','authority']:this.resource==='contacts'?['contact']:this.resource==='deals'?['deal']:this.resource==='quotes'?['quote']:[];}
 async link(row:any){if(!this.selected())return;const kinds=this.linkOptions();const kind=kinds.includes(this.linkKind)?this.linkKind:kinds[0];await this.act('link',{kind,graph8Id:row.id},'POST','Live Graph8 record linked.');}
 async act(action:string,data:any={},method='POST',notice='Saved'){if(this.busy())return false;this.busy.set(true);this.error.set('');try{const t=this.selected();await this.api(`tenders/${t.id}/${action}`,method,{...data,revision:t.revision});await this.reload();this.notice.set(notice);return true;}catch(e){this.error.set(this.message(e));return false;}finally{this.busy.set(false);}}
 async viewDoc(d:any){this.busy.set(true);try{this.document.set(await this.api(`tenders/${this.selected().id}/documents/${d.id}`));this.modal.set('document');}catch(e){this.error.set(this.message(e));}finally{this.busy.set(false);}}
 async upload(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;if(file.size>8*1024*1024){this.error.set('Maximum upload is 8 MB.');return;}const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});await this.act('documents',{name:file.name,base64,includeInBid:this.includeInBid},'POST','Document encrypted and extracted. Review the candidate requirements.');input.value='';}
 addCandidate(c:any){this.open('requirement');this.form={...this.form,title:c.title,source:c.source,mandatory:c.mandatory};}
 async download(path:string,name:string){this.busy.set(true);this.error.set('');try{const r=await fetch('/api/tender/'+path,{headers:this.headers()});if(!r.ok){const e=await r.json();throw new Error(e.error);}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}catch(e){this.error.set(this.message(e));}finally{this.busy.set(false);}}
 async assemble(){if(await this.act('assemble'))this.response=this.selected().response;}
 async saveResponse(){await this.act('response',{response:this.response},'PATCH','Proposal saved. Previous approvals are invalidated.');}
 approved(gate:string){return this.selected()?.approvals.find((a:any)=>a.gate===gate&&a.version===this.selected().version);}
 field(key:string,label:string,type='text',value:any='',options?:any[]){this.form[key]=value;return {key,label,type,options};}
 open(kind:string,row?:any){this.modal.set('form');this.error.set('');this.form={};this.fields=[];this.formMethod='POST';const f=(...args:Parameters<TenderWorkspace['field']>)=>this.field(...args);const t=this.selected();
 if(kind==='tender'||kind==='edit'){this.formTitle=kind==='edit'?'Edit tender':'Register a tender';this.formAction=kind==='edit'?'edit':'create';this.formMethod=kind==='edit'?'PATCH':'POST';const v=kind==='edit'?t:{};this.fields=[f('title','Tender title','text',v.title||''),f('issuer','Issuing authority','text',v.issuer||''),f('reference','Tender reference','text',v.reference||''),f('country','Country / jurisdiction','text',v.country||''),f('currency','Currency (ISO code)','text',v.currency||'USD'),f('deadline','Closing date and time (UTC)','datetime-local',v.deadline?.slice(0,16)||''),f('timezone','Display timezone (IANA)','text',v.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone),f('sourceUrl','Official tender URL (optional)','text',v.sourceUrl||''),f('description','Scope summary','textarea',v.description||''),f('deliveryDays','Required delivery duration (days)','number',v.deliveryDays||120),f('channel','Official clarification channel','select',v.channel||'portal',['portal','email']),f('conflictDeclared','Conflict-of-interest review completed','checkbox',v.conflictDeclared||false)];}
 if(kind==='requirement'){this.formTitle='Add a sourced requirement';this.formAction='requirements';this.fields=[f('title','Requirement','textarea'),f('source','Source document, page and section'),f('mandatory','Mandatory eligibility gate','checkbox',true),f('weight','Evaluation weight','number',1)];}
 if(kind==='compliance'){this.formTitle='Review compliance evidence';this.formAction='requirements/'+row.id;this.formMethod='PATCH';this.fields=[f('status','Compliance status','select',row.status,['unknown','pass','fail']),f('evidenceDocId','Supporting document','select',row.evidenceDocId||'',[{value:'',label:'No document'},...t.documents.map((d:any)=>({value:d.id,label:d.name}))]),f('graph8EvidenceId','Linked Graph8 source','select',row.graph8EvidenceId||'',[{value:'',label:'No Graph8 source'},...Object.values(t.graph8).map((g:any)=>({value:String(g.id),label:g.name||g.id}))]),f('evidence','Evidence excerpt and section','textarea',row.evidence||''),f('response','Our compliance response','textarea',row.response||''),f('expiresAt','Evidence expiry (UTC, optional)','datetime-local',row.expiresAt?.slice(0,16)||'')];}
 if(kind==='cost'){this.formTitle='Add an evidenced cost';this.formAction='costs';this.fields=[f('title','Cost item'),f('category','Category','select','Labour',['Labour','Materials','Licensing','Subcontracting','Equipment','Travel','Cloud','Support','Other']),f('quantity','Quantity','number',1),f('unitCost','Unit cost in '+t.currency,'number',0),f('source','Rate card, quote or estimate basis','textarea')];}
 if(kind==='pricing'){this.formTitle='Revise commercial offer / BAFO';this.formAction='pricing';this.formMethod='PATCH';this.fields=[f('margin','Minimum gross margin (%)','number',t.pricing.margin),f('contingency','Cost contingency (%)','number',t.pricing.contingency),f('tax','Tax rate (%)','number',t.pricing.tax),f('offer','Offer before tax (0 = margin floor)','number',t.pricing.offer)];}
 if(kind==='schedule'){this.formTitle='Plan a work package';this.formAction='schedule';this.fields=[f('title','Work package'),f('days','Calendar days','number',1),f('owner','Responsible team / person'),f('dependency','Starts after','select','',[{value:'',label:'Contract start'},...t.schedule.map((s:any)=>({value:s.id,label:s.title}))])];}
 if(kind==='decision'){this.formTitle='Bid / no-bid decision';this.formAction='decision';this.fields=[f('choice','Decision','select','bid',['bid','no_bid']),f('reason','Evidence and rationale','textarea')];}
 if(kind==='approve'){this.formTitle='Approve '+row+' review';this.formAction='approve';this.form.gate=row;this.fields=[f('note','Approval rationale','textarea')];}
 if(kind==='amendment'){this.formTitle='Record an official addendum';this.formAction='amendments';this.fields=[f('title','Addendum reference'),f('description','What changed?','textarea'),f('source','Official addendum URL','url'),f('deadline','Revised deadline (UTC, optional)','datetime-local'),f('deliveryDays','Revised delivery days (optional)','number','')];}
 if(kind==='clarification'){this.formTitle='Record official clarification';this.formAction='clarifications';this.fields=[f('question','Question','textarea'),f('answer','Official response (optional)','textarea'),f('source','Official source URL','url',t.sourceUrl)];}
 if(kind==='submit'){this.formTitle='Record an external submission receipt';this.formAction='submit';this.fields=[f('receipt','Official submission receipt/reference'),f('submittedAt','Actual submission time (UTC)','datetime-local',new Date().toISOString().slice(0,16)),f('portal','Submission portal URL','url',t.sourceUrl)];}
 if(kind==='outcome'){this.formTitle='Record award or loss';this.formAction='outcome';this.fields=[f('result','Result','select','awarded',['awarded','lost']),f('reason','Outcome evidence and lessons','textarea'),f('source','Official award or evaluation URL','url'),f('winningPrice','Published winning price (optional)','number','')];}
 if(kind==='source'){this.formTitle='Connect a tender JSON feed';this.formAction='source';this.fields=[f('name','Source name'),f('url','Public HTTPS JSON feed URL','url'),f('country','Coverage / jurisdiction','text','Global')];}
 if(kind==='user'){this.formTitle='Add a tender team member';this.formAction='user';this.fields=[f('name','Name'),f('email','Email','email'),f('password','Initial password (12+ characters)','password'),f('role','Role','select','contributor',['contributor','issuer','reviewer','viewer','administrator'])];}
 if(kind==='crm'){this.formTitle='Create a real Graph8 deal';this.formAction='crm';this.form.approved=true;this.fields=[f('pipelineId','Graph8 pipeline ID from live intelligence'),f('ownerId','Graph8 owner email / ID')];}
 if(kind==='partner'){this.formTitle='Shortlist a Graph8 partner';this.formAction='partners';this.form.companyId=row.id;this.fields=[f('gap','Capability gap this company may address','textarea')];}
 if(kind==='quote'){this.formTitle='Create a real Graph8 draft quote';this.formAction='quote';this.form.approved=true;this.fields=[];}
 }
 optional(f:any){return /optional|expiry|Supporting document|Linked Graph8|Official response/.test(f.label);}
 async save(){const data={...this.form};for(const field of this.fields)if(field.type==='datetime-local'&&data[field.key])data[field.key]=new Date(data[field.key]+'Z').toISOString();if(this.formAction==='schedule'){data.dependencies=data.dependency?[data.dependency]:[];delete data.dependency;}
 if(['create','source','user'].includes(this.formAction)){this.busy.set(true);this.error.set('');try{const path=this.formAction==='create'?'tenders':this.formAction==='source'?'sources':'team';const result=await this.api(path,'POST',data);await this.reload();if(result.tender)this.pick(result.tender);if(path==='sources')this.sources.set(await this.api('sources'));if(path==='team')this.team.set(await this.api('team'));this.notice.set(result.duplicate?'This tender was already registered. Opened the existing record.':'Created successfully.');this.modal.set('');}catch(e){this.error.set(this.message(e));}finally{this.busy.set(false);}return;}
 if(await this.act(this.formAction==='edit'?'':this.formAction,data,this.formMethod))this.modal.set('');
 }
 async sourceAction(source:any,action:string){this.busy.set(true);this.error.set('');try{await this.api(`sources/${source.id}${action==='sync'?'/sync':''}`,action==='sync'?'POST':'PATCH',action==='sync'?{}:{enabled:!source.enabled});this.sources.set(await this.api('sources'));await this.reload();this.notice.set('Source updated.');}catch(e){this.error.set(this.message(e));}finally{this.busy.set(false);}}
}
