import {graph8ConnectionError} from '../connection-error.mjs';
import {createMarketplace} from './marketplace.mjs';
import {createBidFlow} from './bidflow/routes.mjs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {AppError,text,number,safeUrl} from '../domain.mjs';
import {openTenderDb} from './database.mjs';
import {orgContext,readResource,liveRecord,liveCall,can} from './graph8.mjs';
import {newTender,uid,stamp,instant,qualification,readiness,review,assemble,invalidate,timeline,costing} from './model.mjs';
import {extractDocument,bidPackage} from './documents.mjs';
import {fetchSource} from './sources.mjs';
import {sessionUser,createUser,publicUser,requireRole,login} from './auth.mjs';

export function createTenderApi(root,dependencies={}){
 const {orgContext:context=orgContext,readResource:read=readResource}=dependencies;
 const db=openTenderDb(process.env.TENDER_DB||resolve(root,'server/data/tenders.sqlite')),locks=new Set(),limits=new Map();
 const bidflow=createBidFlow(db);
 const marketplace=createMarketplace(db,{readResource:read,hooks:{onPublish:bidflow.onPublish,onAward:bidflow.onAward}});
 const limited=(key,max=100)=>{const at=Date.now();let r=limits.get(key);if(!r||r.until<at)r={count:0,until:at+60000};r.count++;limits.set(key,r);if(limits.size>10000)for(const [k,v]of limits)if(v.until<at)limits.delete(k);if(r.count>max)throw new AppError('Too many requests. Try again in a minute.',429);};
 const hydrate=t=>({...t,assessment:qualification(t),readiness:readiness(t)});
 const edits=['administrator','contributor','reviewer'],reviews=['administrator','reviewer'];
 function touch(org,id,user,action,b,fn){if(locks.has(id))throw new AppError('An external action is running for this tender.',409);if(!Number.isInteger(b.revision))throw new AppError('Refresh the tender before editing (revision required).',409);return hydrate(db.update(org,'tender',id,user.id,action,t=>{if(['awarded','lost','no_bid'].includes(t.stage)&&!['outcome','reopen'].includes(action))throw new AppError('Closed pursuits are read-only. Reopen to revise.');fn(t);},b.revision));}
 function ensureDoc(org,t,id){if(!t.documents.some(d=>d.id===id))throw new AppError('Document is not attached to this tender.',404);return db.get(org,'document',id);}
 function insert(org,b,actor){const tender=newTender(b),existing=db.list(org,'tender').find(x=>x.fingerprint===tender.fingerprint);if(existing)return {duplicate:true,tender:hydrate(existing)};return {duplicate:false,tender:hydrate(db.create(org,'tender',tender,actor))};}
 async function syncSource(org,id,actor){const source=db.get(org,'source',id),rows=await fetchSource(source.url);rows.forEach(newTender);let added=0,duplicates=0;for(const row of rows){const result=insert(org,row,actor);result.duplicate?duplicates++:added++;}db.update(org,'source',id,actor,'source:checked',s=>{s.checkedAt=stamp();s.lastResult={added,duplicates};s.error=null;});return {added,duplicates};}
 // SEED_USERS='[{"email":"…","name":"…","password":"…","role":"administrator|issuer|contributor"}]' recreates
 // accounts when the database is empty — for demo hosts whose disk is wiped on restart.
 const seeded=new Set();
 function seed(orgId){if(seeded.has(orgId)||!process.env.SEED_USERS)return;seeded.add(orgId);if(db.list(orgId,'user').length)return;
  let rows;try{rows=JSON.parse(process.env.SEED_USERS);}catch{console.error('SEED_USERS is not valid JSON; no accounts seeded.');return;}
  for(const u of Array.isArray(rows)?rows:[]){try{createUser(db,orgId,u,['administrator','issuer','contributor','reviewer','viewer'].includes(u.role)?u.role:'contributor');}catch(e){console.error('Seed user skipped:',u?.email,e.message);}}}
 async function route(req,res,url,b){
  const p=url.pathname.split('/').filter(Boolean).slice(2),method=req.method;let org;
  try{org=await context();}catch(e){throw graph8ConnectionError(e);}
  seed(org.id);
  const user=sessionUser(db,org.id,req),send=(value,status=200)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(value));};
  limited(`${org.id}:${req.socket.remoteAddress}`);
  if(p[0]==='session'&&method==='GET')return send({org,user:user?publicUser(user):null,needsBootstrap:db.list(org.id,'user').length===0,capabilities:{crmWrite:can(org,'deals:write'),pipelineWrite:can(org,'campaigns:write'),quotes:can(org,'quotes:run'),workflow:can(org,'workflows:run')}});
  if(p[0]==='bootstrap'&&method==='POST'){if(db.list(org.id,'user').length)throw new AppError('An administrator is already configured.',409);createUser(db,org.id,b,'administrator');return send(login(db,org.id,b),201);}
  if(p[0]==='login'&&method==='POST'){limited(`login:${org.id}:${req.socket.remoteAddress}`,10);return send(login(db,org.id,b));}
  requireRole(user,['administrator','contributor','reviewer','viewer','issuer']);
  if(p[0]==='logout'&&method==='POST'){const id=createHash('sha256').update(req.headers['x-tender-session']).digest('hex');db.update(org.id,'session',id,user.id,'session:logout',s=>s.expires=0);return send({success:true});}
  if(p[0]==='market')return marketplace.route({org,user,p,method,b,send,res});
  if(p[0]==='bidflow')return bidflow.route({org,user,p,method,b,send,url});
  if(['issuer','contributor'].includes(user.role))throw new AppError('Use the role-specific marketplace for this account.',403);
  if(p[0]==='team'){requireRole(user,['administrator']);if(method==='GET')return send(db.list(org.id,'user').map(publicUser));if(method==='POST'){if(!['administrator','contributor','reviewer','viewer','issuer'].includes(b.role))throw new AppError('Select a valid role.');return send(publicUser(createUser(db,org.id,b,b.role)),201);}}
  if(p[0]==='audit'&&method==='GET')return send({verified:db.verifyAudit(org.id),events:db.audit(org.id)});
  if(p[0]==='live'&&method==='GET'){const page=Number(url.searchParams.get('page')||1);if(!Number.isInteger(page)||page<1||page>10000)throw new AppError('Invalid page.');return send(await read(p[1],page,url.searchParams.get('q')||''));}
  if(p[0]==='sources'){
   if(method==='GET')return send(db.list(org.id,'source'));requireRole(user,edits);
   if(method==='POST'&&!p[1])return send(db.create(org.id,'source',{id:uid(),name:text(b.name,'Source name'),url:safeUrl(b.url),country:text(b.country||'Global','Country'),enabled:false,createdAt:stamp()},user.id),201);
   if(method==='PATCH')return send(db.update(org.id,'source',p[1],user.id,'source:configuration',s=>s.enabled=b.enabled===true));
   if(method==='POST'&&p[2]==='sync'){try{return send(await syncSource(org.id,p[1],user.id));}catch(e){db.update(org.id,'source',p[1],user.id,'source:error',s=>{s.error=e.message;s.checkedAt=stamp();});throw e;}}
  }
  if(p[0]!=='tenders')throw new AppError('Tender API route not found.',404);
  if(method==='GET'&&!p[1])return send({tenders:db.list(org.id,'tender').map(hydrate),org,checkedAt:stamp()});
  if(method==='POST'&&!p[1]){requireRole(user,edits);return send(insert(org.id,b,user.id),201);}
  const id=p[1],action=p[2],t=db.get(org.id,'tender',id);
  if(method==='GET'&&!action)return send(hydrate(t));
  if(method==='GET'&&action==='documents'){const d=ensureDoc(org.id,t,p[3]);if(url.searchParams.get('download')==='true'){res.writeHead(200,{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename="${d.name.replace(/[^a-zA-Z0-9._-]/g,'_')}"`,'Cache-Control':'no-store'});return res.end(Buffer.from(d.base64,'base64'));}const {base64,...metadata}=d;return send(metadata);}
  if(method==='GET'&&action==='package'){const assessment=readiness(t),checks=review(t);if(!assessment.ready||checks.findings.some(f=>f.severity==='blocker'))throw new AppError('Resolve review findings and approvals before exporting a submission package.',409);const buffer=await bidPackage(t,t.documents.filter(d=>d.includeInBid).map(d=>ensureDoc(org.id,t,d.id)),assessment);res.writeHead(200,{'Content-Type':'application/zip','Content-Disposition':`attachment; filename="bid-${t.reference.replace(/[^a-zA-Z0-9_-]/g,'_')}-v${t.version}.zip"`,'Cache-Control':'no-store'});return res.end(buffer);}
  requireRole(user,edits);
  if(method==='PATCH'&&!action)return send(touch(org.id,id,user,'tender:edited',b,row=>{const merged=newTender({...row,...b});for(const field of ['title','issuer','reference','country','currency','deadline','timezone','sourceUrl','description','channel','deliveryDays'])row[field]=merged[field];if(db.list(org.id,'tender').some(x=>x.id!==id&&x.fingerprint===merged.fingerprint))throw new AppError('That tender reference already exists.',409);row.fingerprint=merged.fingerprint;row.conflictDeclared=b.conflictDeclared===true;invalidate(row,'Tender details changed');}));
  if(action==='link'&&method==='POST'){const kind=text(b.kind,'Graph8 entity');if(!['supplier','authority','deal','quote','contact'].includes(kind))throw new AppError('Invalid entity type.');const types={supplier:'companies',authority:'companies',deal:'deals',quote:'quotes',contact:'contacts'},data=await liveRecord(types[kind],b.graph8Id);return send(touch(org.id,id,user,'graph8:linked',b,row=>{row.graph8[kind]={id:b.graph8Id,name:data.name||data.title||data.quote_number||[data.first_name,data.last_name].filter(Boolean).join(' '),data,checkedAt:stamp()};if(row.external?.status==='uncertain'&&['deal','quote'].includes(kind))row.external={...row.external,status:'reconciled',at:stamp()};invalidate(row,'Graph8 source refreshed');}));}
  if(action==='documents'&&method==='POST'){const name=text(b.name,'Filename',200);if(typeof b.base64!=='string'||b.base64.length>12*1024*1024||! /^[A-Za-z0-9+/]*={0,2}$/.test(b.base64))throw new AppError('Invalid or oversized document.');const buffer=Buffer.from(b.base64,'base64'),hash=createHash('sha256').update(buffer).digest('hex');if(t.documents.some(d=>d.sha256===hash))throw new AppError('This document is already attached.',409);const parsed=await extractDocument(name,buffer),doc={id:uid(),name,sha256:hash,base64:b.base64,...parsed,createdAt:stamp(),tenderId:id};db.create(org.id,'document',doc,user.id);return send(touch(org.id,id,user,'document:uploaded',b,row=>{row.documents.push({id:doc.id,name,sha256:hash,size:buffer.length,includeInBid:b.includeInBid===true,createdAt:doc.createdAt,candidates:parsed.candidates.length,warning:parsed.warning});invalidate(row,'Document added');}));}
  if(action==='requirements'&&method==='POST')return send(touch(org.id,id,user,'requirement:added',b,row=>{row.requirements.push({id:uid(),title:text(b.title,'Requirement',1500),mandatory:b.mandatory===true,source:text(b.source,'Tender page or section',1000),status:'unknown',evidence:'',response:'',weight:number(b.weight??1,'Weight',0,100)});invalidate(row,'Requirement added');}));
  if(action==='requirements'&&method==='PATCH')return send(touch(org.id,id,user,'requirement:reviewed',b,row=>{const r=row.requirements.find(x=>x.id===p[3]);if(!r)throw new AppError('Requirement not found.',404);if(!['pass','fail','unknown'].includes(b.status))throw new AppError('Invalid compliance status.');if(b.status==='pass'){requireRole(user,reviews);if(!b.evidenceDocId&&!b.graph8EvidenceId)throw new AppError('Attach a source document or verified Graph8 evidence.');if(b.evidenceDocId)ensureDoc(org.id,row,b.evidenceDocId);if(b.graph8EvidenceId&&!Object.values(row.graph8).some(x=>String(x.id)===String(b.graph8EvidenceId)))throw new AppError('Link the Graph8 source first.');r.evidence=text(b.evidence,'Evidence excerpt and section',4000);}else r.evidence=String(b.evidence||'').slice(0,4000);r.status=b.status;r.response=String(b.response||'').slice(0,10000);r.evidenceDocId=b.evidenceDocId||null;r.graph8EvidenceId=b.graph8EvidenceId||null;r.expiresAt=b.expiresAt?instant(b.expiresAt,'Evidence expiry'):null;r.reviewedBy=user.name;r.reviewedAt=stamp();invalidate(row,'Compliance evidence changed');}));
  if(action==='costs'&&method==='POST')return send(touch(org.id,id,user,'cost:added',b,row=>{row.costs.push({id:uid(),title:text(b.title,'Cost item'),category:text(b.category||'Labour','Category'),quantity:number(b.quantity,'Quantity',0.0001,1000000),unitCost:number(b.unitCost,'Unit cost',0,1000000000),source:text(b.source,'Estimate source',2000)});invalidate(row,'Cost estimate changed');}));
  if(action==='costs'&&method==='DELETE')return send(touch(org.id,id,user,'cost:removed',b,row=>{row.costs=row.costs.filter(c=>c.id!==p[3]);invalidate(row,'Cost estimate changed');}));
  if(action==='pricing'&&method==='PATCH')return send(touch(org.id,id,user,'pricing:revised',b,row=>{row.pricing={margin:number(b.margin,'Minimum margin',0,95),contingency:number(b.contingency,'Contingency',0,200),tax:number(b.tax,'Tax rate',0,100),offer:number(b.offer,'Proposed offer',0,1000000000000)};invalidate(row,'Commercial offer changed');}));
  if(action==='schedule'&&method==='POST')return send(touch(org.id,id,user,'schedule:added',b,row=>{row.schedule.push({id:uid(),title:text(b.title,'Work package'),days:number(b.days,'Duration',1,3650),owner:text(b.owner,'Delivery owner'),dependencies:Array.isArray(b.dependencies)?b.dependencies:[]});timeline(row);invalidate(row,'Delivery plan changed');}));
  if(action==='schedule'&&method==='DELETE')return send(touch(org.id,id,user,'schedule:removed',b,row=>{if(row.schedule.some(x=>x.dependencies.includes(p[3])))throw new AppError('Remove dependent work packages first.');row.schedule=row.schedule.filter(x=>x.id!==p[3]);invalidate(row,'Delivery plan changed');}));
  if(action==='decision'&&method==='POST'){requireRole(user,reviews);return send(touch(org.id,id,user,'bid:decision',b,row=>{if(!['bid','no_bid'].includes(b.choice))throw new AppError('Choose bid or no bid.');if(b.choice==='bid'&&qualification(row).eligibility!=='eligible')throw new AppError('Mandatory eligibility must pass before approving a bid.',409);row.decision={choice:b.choice,reason:text(b.reason,'Decision rationale',4000),by:user.name,at:stamp()};row.stage=b.choice==='bid'?'bid_preparation':'no_bid';invalidate(row,'Pursuit decision recorded');}));}
  if(action==='response'&&method==='PATCH')return send(touch(org.id,id,user,'proposal:edited',b,row=>{row.response=text(b.response,'Proposal',100000);invalidate(row,'Proposal revised');}));
  if(action==='assemble'&&method==='POST')return send(touch(org.id,id,user,'proposal:assembled',b,row=>{row.response=assemble(row,row.graph8.supplier?.data);invalidate(row,'Evidence-based draft assembled');}));
  if(action==='versions'&&method==='POST')return send(touch(org.id,id,user,'version:saved',b,row=>{if(row.versions.length>=100)throw new AppError('Version limit reached.');row.versions.unshift({id:uid(),version:row.version,at:stamp(),by:user.name,response:row.response,requirements:structuredClone(row.requirements),pricing:costing(row),note:text(b.note||'Review snapshot','Version note',1000)});}));
  if(action==='review'&&method==='POST')return send(touch(org.id,id,user,'review:completed',b,row=>{row.reviews.unshift(review(row));row.reviews=row.reviews.slice(0,50);if(row.stage==='bid_preparation')row.stage='internal_review';}));
  if(action==='approve'&&method==='POST'){requireRole(user,reviews);return send(touch(org.id,id,user,'approval:recorded',b,row=>{if(!['technical','commercial','legal','submission'].includes(b.gate))throw new AppError('Invalid approval gate.');const q=qualification(row);if(q.blockers.length)throw new AppError(q.blockers.join(' '),409);if(!row.response.trim()||/\[(TODO|NEEDS|VERIFY)|\bTBD\b/i.test(row.response))throw new AppError('Complete the proposal before approving.',409);if(row.requirements.some(r=>r.mandatory&&!r.response?.trim()))throw new AppError('Every mandatory requirement needs a response.',409);row.approvals=row.approvals.filter(a=>a.gate!==b.gate);row.approvals.push({id:uid(),gate:b.gate,version:row.version,by:user.name,actor:user.id,at:stamp(),note:text(b.note,'Approval rationale',2000)});if(readiness(row).ready)row.stage='ready';}));}
  if(action==='amendments'&&method==='POST')return send(touch(org.id,id,user,'amendment:recorded',b,row=>{row.amendments.unshift({id:uid(),title:text(b.title,'Addendum'),description:text(b.description,'Change summary',10000),source:safeUrl(b.source),at:stamp(),acknowledged:false,previousDeadline:row.deadline});if(b.deadline)row.deadline=instant(b.deadline);if(b.deliveryDays)row.deliveryDays=number(b.deliveryDays,'Delivery days',1,3650);for(const r of row.requirements)if(r.mandatory)r.status='unknown';row.decision=null;invalidate(row,'Addendum requires requalification');}));
  if(action==='amendments'&&method==='PATCH'){requireRole(user,reviews);return send(touch(org.id,id,user,'amendment:acknowledged',b,row=>{const a=row.amendments.find(x=>x.id===p[3]);if(!a)throw new AppError('Addendum not found.',404);a.acknowledged=true;a.reviewedBy=user.name;a.reviewedAt=stamp();}));}
  if(action==='clarifications'&&method==='POST')return send(touch(org.id,id,user,'clarification:added',b,row=>{row.clarifications.unshift({id:uid(),question:text(b.question,'Question',4000),answer:String(b.answer||'').slice(0,6000),source:safeUrl(b.source||row.sourceUrl),channel:row.channel,at:stamp()});invalidate(row,'Clarification recorded');}));
  if(action==='partners'&&method==='POST'){const company=await liveRecord('companies',b.companyId);return send(touch(org.id,id,user,'partner:shortlisted',b,row=>{if(row.partners.some(x=>String(x.companyId)===String(b.companyId)))throw new AppError('Partner already shortlisted.');row.partners.push({id:uid(),companyId:b.companyId,name:company.name,gap:text(b.gap,'Capability gap',2000),status:'unverified',source:'Graph8 CRM',checkedAt:stamp()});invalidate(row,'Partner shortlist changed');}));}
  if(action==='submit'&&method==='POST'){requireRole(user,reviews);return send(touch(org.id,id,user,'submission:recorded',b,row=>{if(row.stage==='submitted')throw new AppError('Submission is already recorded.',409);const r=readiness(row);if(!r.ready)throw new AppError(r.blockers.join(' '),409);if(review(row).findings.some(f=>f.severity==='blocker'))throw new AppError('Resolve proposal review findings first.');const submittedAt=instant(b.submittedAt,'Submission time');if(Date.parse(submittedAt)>Date.now()+60000||Date.parse(submittedAt)>Date.parse(row.deadline))throw new AppError('Submission time must be before the deadline and not in the future.');row.submissions.push({id:uid(),version:row.version,at:submittedAt,recordedAt:stamp(),by:user.name,receipt:text(b.receipt,'Official receipt/reference',2000),portal:safeUrl(b.portal||row.sourceUrl),method:'Human-confirmed external submission'});row.stage='submitted';}));}
  if(action==='stage'&&method==='PATCH'){requireRole(user,reviews);return send(touch(org.id,id,user,'pursuit:stage',b,row=>{const next={discovered:['qualifying'],submitted:['clarification','shortlisted','negotiation'],clarification:['shortlisted','negotiation'],shortlisted:['negotiation']};if(!next[row.stage]?.includes(b.stage))throw new AppError('That stage transition is not available.');row.stage=b.stage;}));}
  if(action==='outcome'&&method==='POST'){requireRole(user,reviews);return send(touch(org.id,id,user,'outcome',b,row=>{if(!['submitted','clarification','shortlisted','negotiation','awarded','lost'].includes(row.stage))throw new AppError('Record submission before an award or loss.');if(!['awarded','lost'].includes(b.result))throw new AppError('Choose awarded or lost.');row.stage=b.result;row.outcome={result:b.result,reason:text(b.reason,'Outcome evidence and lessons',10000),source:safeUrl(b.source),winningPrice:b.winningPrice===null||b.winningPrice===''||b.winningPrice===undefined?null:number(b.winningPrice,'Published winning price',0,1000000000000),at:stamp(),by:user.name};}));}
  if(action==='reopen'&&method==='POST'){requireRole(user,reviews);return send(touch(org.id,id,user,'reopen',b,row=>{row.stage='qualifying';row.decision=null;invalidate(row,'Pursuit reopened');}));}
  if(action==='crm'&&method==='POST'){
   requireRole(user,reviews);if(!can(org,'deals:write'))throw new AppError('Enable deals:write on the server API key to create a native Graph8 deal.',403);if(t.graph8.deal)throw new AppError('A Graph8 deal is already linked.',409);if(!t.graph8.contact)throw new AppError('Link the issuing authority’s Graph8 contact first.');
   const pipelines=await readResource('pipelines'),pipeline=pipelines.rows.find(x=>String(x.id)===String(b.pipelineId));if(!pipeline)throw new AppError('Select an existing Graph8 pipeline.');const owner=text(b.ownerId,'Graph8 owner identifier',250);const request={name:t.title,contact_ids:[Number(t.graph8.contact.id)],owner_id:owner,pipeline_id:pipeline.id,amount:costing(t).offer,currency:t.currency,description:`Tender ${t.reference}\n${t.sourceUrl}\nClosing ${t.deadline}`};
   return send(await external(id,org,user,b,'crm',()=>liveCall('create_deal_deals_post',{body:request},{idempotencyKey:`tender-${id}-deal`}),result=>({kind:'deal',id:result.id,data:result,name:result.name})));
  }
  if(action==='quote'&&method==='POST'){
   requireRole(user,reviews);if(!can(org,'quotes:run'))throw new AppError('Graph8 quotes:run permission is required.',403);if(!t.graph8.deal)throw new AppError('Link a Graph8 deal first.');if(!t.approvals.some(a=>a.gate==='commercial'&&a.version===t.version))throw new AppError('Approve the current commercial offer first.');if(t.graph8.quote)throw new AppError('A quote is already linked; revise it in Graph8.');const c=costing(t);
   return send(await external(id,org,user,b,'quote',()=>liveCall('create_quote_quotes_post',{body:{title:t.title,deal_id:t.graph8.deal.id,currency:t.currency,tax_amount:Math.round(c.tax*100),line_items:[{product_name:t.title,quantity:1,unit_amount:Math.round(c.offer*100),billing_frequency:'one_time'}],notes:`Tender ${t.reference}, local bid version ${t.version}. Draft only.`}},{idempotencyKey:`tender-${id}-quote-v${t.version}`}),result=>({kind:'quote',id:result.id,data:result,name:result.title})));
  }
  throw new AppError('Tender action not found.',404);
 }
 async function external(id,org,user,b,action,fn,map){
  if(locks.has(id))throw new AppError('Action already running.',409);if(b.approved!==true)throw new AppError('Review and approve the external action.');if(!Number.isInteger(b.revision))throw new AppError('Revision required.',409);
  locks.add(id);try{db.update(org.id,'tender',id,user.id,`${action}:started`,t=>{if(['uncertain','running'].includes(t.external?.status))throw new AppError('Reconcile the previous uncertain action in Graph8 before retrying.',409);t.external={action,status:'running',at:stamp()};},b.revision);
   try{const response=await fn(),value=response.data||response,link=map(value);if(!link.id)throw new Error('Graph8 did not return a record ID.');return hydrate(db.update(org.id,'tender',id,user.id,`${action}:completed`,t=>{t.graph8[link.kind]={...link,checkedAt:stamp()};t.external={action,status:'completed',at:stamp()};}));}
   catch(e){db.update(org.id,'tender',id,user.id,`${action}:uncertain`,t=>t.external={action,status:'uncertain',at:stamp()});throw new AppError('The Graph8 write was not confirmed. Inspect Graph8 and link the existing record before retrying.',502);}
  }finally{locks.delete(id);}
 }
 let running=false;const timer=setInterval(async()=>{if(running)return;running=true;try{const org=await context();await marketplace.tick(org.id);try{await bidflow.tick(org.id);}catch{}for(const s of db.list(org.id,'source')){if(!s.enabled||s.checkedAt&&Date.now()-Date.parse(s.checkedAt)<15*60000)continue;try{await syncSource(org.id,s.id,'source-monitor');}catch(e){db.update(org.id,'source',s.id,'source-monitor','source:error',r=>{r.checkedAt=stamp();r.error=e.message;});}}}catch{}finally{running=false;}},60000);timer.unref();
 return {route,close(){clearInterval(timer);db.close();}};
}
