import {randomBytes,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {AppError,text} from '../domain.mjs';
export const publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role});
export function passwordHash(password,salt=randomBytes(16).toString('hex')){if(typeof password!=='string'||password.length<12||password.length>200)throw new AppError('Use a password of 12–200 characters.');return `${salt}:${scryptSync(password,salt,32).toString('hex')}`;}
export function matches(password,encoded){if(typeof password!=='string'||password.length>200)return false;const [salt,hash]=encoded.split(':'),a=Buffer.from(hash,'hex'),b=scryptSync(password,salt,32);return a.length===b.length&&timingSafeEqual(a,b);}
export function createUser(db,org,b,role){const email=text(b.email,'Email',250).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new AppError('Enter a valid email.');if(db.list(org,'user').some(u=>u.email===email))throw new AppError('An account already exists.',409);return db.create(org,'user',{id:db.id(),email,name:text(b.name,'Name',100),role,password:passwordHash(b.password)},'administrator');}
export function sessionUser(db,org,req){const token=req.headers['x-tender-session'];if(typeof token!=='string')return null;const id=createHash('sha256').update(token).digest('hex');try{const session=db.get(org,'session',id);if(session.expires<Date.now())return null;return db.get(org,'user',session.userId);}catch{return null;}}
export function requireRole(user,roles){if(!user)throw new AppError('Sign in to Tender Workspace.',401);if(!roles.includes(user.role))throw new AppError('Your tender role does not allow this action.',403);}
export function login(db,org,b){const user=db.list(org,'user').find(u=>u.email===String(b.email||'').toLowerCase().trim());if(!user||!matches(b.password,user.password))throw new AppError('Email or password is incorrect.',401);const token=randomBytes(32).toString('hex');db.create(org,'session',{id:createHash('sha256').update(token).digest('hex'),userId:user.id,expires:Date.now()+8*3600000},user.id);return {token,user:publicUser(user)};}
