import { createHash, randomUUID } from 'node:crypto';
import { AppError, text, number, safeUrl } from '../domain.mjs';
export const stages = ['discovered', 'qualifying', 'bid_preparation', 'internal_review', 'ready', 'submitted', 'clarification', 'shortlisted', 'negotiation', 'awarded', 'lost', 'no_bid'];
export const uid = () => randomUUID(), stamp = () => new Date().toISOString();
export function instant(v, label = 'Deadline') { if (typeof v !== 'string' || !/(Z|[+-]\d{2}:\d{2})$/.test(v) || !Number.isFinite(Date.parse(v))) throw new AppError(`${label} must include a timezone offset.`); return new Date(v).toISOString(); }
export function currency(v) { if (typeof v !== 'string' || ! /^[A-Z]{3}$/.test(v)) throw new AppError('Use a three-letter currency code.'); try { new Intl.NumberFormat('en', { style: 'currency', currency: v }).format(0); } catch { throw new AppError('Invalid currency.'); } return v; }
export function fingerprint(t) { return createHash('sha256').update([t.issuer, t.reference, t.country].map(s => s.trim().toLowerCase().replace(/\s+/g, ' ')).join('|')).digest('hex'); }
export function newTender(b) {
    const t = { id: uid(), title: text(b.title, 'Title'), issuer: text(b.issuer, 'Issuing authority'), reference: text(b.reference, 'Tender reference', 200), country: text(b.country, 'Country', 100), currency: currency(b.currency || 'USD'), deadline: instant(b.deadline), timezone: text(b.timezone || 'UTC', 'Timezone', 100), sourceUrl: tenderUrl(b.sourceUrl), description: typeof b.description === 'string' ? b.description.slice(0, 30000) : '', channel: b.channel === 'email' ? 'email' : 'portal', deliveryDays: number(b.deliveryDays || 120, 'Delivery days', 1, 3650), stage: 'discovered', version: 1, createdAt: stamp(), updatedAt: stamp(), requirements: [], documents: [], costs: [], schedule: [], partners: [], clarifications: [], amendments: [], versions: [], approvals: [], submissions: [], reviews: [], graph8: {}, decision: null, pricing: { margin: 20, contingency: 10, tax: 0, offer: 0 }, response: '', outcome: null, conflictDeclared: false };
    try { new Intl.DateTimeFormat('en', { timeZone: t.timezone }); } catch { throw new AppError('Use a valid IANA timezone, such as Asia/Karachi.'); }
    t.fingerprint = fingerprint(t); return t;
}
export function costing(t) { const round = n => Math.round((n + Number.EPSILON) * 100) / 100; const base = round(t.costs.reduce((n, c) => n + c.quantity * c.unitCost, 0)); const contingency = round(base * t.pricing.contingency / 100), cost = round(base + contingency); const floor = round(cost / (1 - t.pricing.margin / 100)), offer = t.pricing.offer || floor, tax = round(offer * t.pricing.tax / 100); return { base, contingency, cost, floor, offer, tax, total: round(offer + tax), margin: offer ? round((offer - cost) / offer * 100) : 0, currency: t.currency }; }
export function timeline(t) { const rows = new Map(t.schedule.map(x => [x.id, x])), done = new Map(), visiting = new Set(); function end(id) { if (done.has(id)) return done.get(id); if (visiting.has(id)) throw new AppError('Schedule contains a circular dependency.'); const r = rows.get(id); if (!r) throw new AppError('Schedule dependency not found.'); visiting.add(id); const start = Math.max(0, ...r.dependencies.map(end)); const value = start + r.days; visiting.delete(id); done.set(id, value); return value; } for (const row of t.schedule) end(row.id); const days = Math.max(0, ...done.values()); return { days, required: t.deliveryDays, buffer: t.deliveryDays - days, feasible: t.schedule.length > 0 && days <= t.deliveryDays, rows: t.schedule.map(r => ({ ...r, start: done.get(r.id) - r.days, end: done.get(r.id) })) }; }
export function qualification(t) { const mandatory = t.requirements.filter(r => r.mandatory), failed = mandatory.filter(r => r.status === 'fail'), unknown = mandatory.filter(r => r.status !== 'pass' && r.status !== 'fail'), valid = r => r.status === 'pass' && r.evidence && (!r.expiresAt || Date.parse(r.expiresAt) > Date.now()); const passed = t.requirements.filter(valid); const expired = mandatory.filter(r => r.status === 'pass' && !valid(r)); const eligibility = failed.length ? 'ineligible' : !mandatory.length || unknown.length || expired.length ? 'unverified' : 'eligible'; const coverage = t.requirements.length ? Math.round(passed.length / t.requirements.length * 100) : 0; const c = costing(t), time = timeline(t); const blockers = []; if (eligibility !== 'eligible') blockers.push(`${failed.length} failed and ${unknown.length + expired.length} unresolved mandatory requirements${!mandatory.length ? ' (no mandatory requirements defined)' : ''}.`); if (Date.parse(t.deadline) <= Date.now()) blockers.push('Submission deadline has passed.'); if (!time.feasible) blockers.push(t.schedule.length ? 'Delivery plan exceeds the required duration.' : 'Delivery schedule is missing.'); if (!t.costs.length || c.cost <= 0) blockers.push('A supported cost estimate is missing.'); if (c.margin + 0.01 < t.pricing.margin) blockers.push('Offer is below the approved margin floor.'); if (!t.conflictDeclared) blockers.push('Conflict-of-interest review is not recorded.'); return { eligibility, coverage, passed: passed.length, total: t.requirements.length, blockers, cost: c, timeline: time, recommendation: eligibility === 'ineligible' || (t.schedule.length && !time.feasible) ? 'no_bid' : blockers.length ? 'review_required' : 'pursue' }; }
export function invalidate(t, reason) { t.version++; t.approvals = []; if (['ready', 'internal_review'].includes(t.stage)) t.stage = 'bid_preparation'; t.lastChange = reason; }
export function readiness(t) { const q = qualification(t), blockers = [...q.blockers]; if (t.decision?.choice !== 'bid') blockers.push('Record an approved bid decision.'); if (!t.response.trim()) blockers.push('Proposal response is missing.'); if (t.amendments.some(x => !x.acknowledged)) blockers.push('An amendment is awaiting review.'); for (const gate of ['technical', 'commercial', 'legal', 'submission']) if (!t.approvals.some(a => a.gate === gate && a.version === t.version)) blockers.push(`${gate} approval is missing for version ${t.version}.`); return { ...q, blockers, ready: blockers.length === 0 }; }
export function review(t) { const result = readiness(t); const findings = result.blockers.map(message => ({ severity: 'blocker', message })); for (const r of t.requirements) { if (!r.response?.trim()) findings.push({ severity: r.mandatory ? 'blocker' : 'warning', message: `Response missing: ${r.title}` }); } if (/\[(TODO|NEEDS|VERIFY)|\bTBD\b/i.test(t.response)) findings.push({ severity: 'blocker', message: 'Proposal contains unresolved placeholders.' }); return { id: uid(), at: stamp(), version: t.version, method: 'Deterministic evidence and completeness checks; not an independent AI scoring panel.', findings }; }
export function assemble(t, supplier) { const q = qualification(t); return [`# ${t.title}`, `Tender reference: ${t.reference}\nAuthority: ${t.issuer}\nSubmission deadline: ${t.deadline}`, `## Bidder\n${supplier?.name || '[NEEDS VERIFIED SUPPLIER]'}${supplier?.domain ? ' · ' + supplier.domain : ''}`, `## Executive summary\n${t.description || '[NEEDS SCOPE SUMMARY]'}`, `## Compliance response`, ...t.requirements.map(r => `### ${r.title}\n${r.response || '[NEEDS APPROVED RESPONSE]'}\nEvidence: ${r.evidence || '[NEEDS EVIDENCE]'}\nTender source: ${r.source || '[NEEDS SOURCE SECTION]'}`), `## Delivery plan\n${q.timeline.rows.map(r => `${r.title}: day ${r.start}–${r.end}; owner: ${r.owner}`).join('\n') || '[NEEDS DELIVERY PLAN]'}`, `## Commercial offer\nCurrency: ${t.currency}\nOffer before tax: ${q.cost.offer.toFixed(2)}\nTax: ${q.cost.tax.toFixed(2)}\nTotal: ${q.cost.total.toFixed(2)}`, `## Clarifications\n${t.clarifications.map(c => `${c.question}\n${c.answer || 'Awaiting official response'}`).join('\n\n') || 'No clarifications recorded.'}`].join('\n\n'); }

export function tenderUrl(value) { if (value === undefined || value === null || !String(value).trim()) return ''; let raw = String(value).trim(); if (!/^[a-z][a-z0-9+.-]*:/i.test(raw)) raw = 'https://' + raw; try { return safeUrl(raw); } catch { throw new AppError('Official tender URL must be a valid HTTPS address, or leave it blank for a tender created here.'); } }
