import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,extname} from 'node:path';
import {chromium} from '@playwright/test';
import {openTenderDb} from '../server/tender/database.mjs';
import {createUser} from '../server/tender/auth.mjs';
import {createTenderApi} from '../server/tender/api.mjs';

test('Browser: issuer publishes without URL, bidder submits, issuer receives and evaluates', {timeout:120000},async()=>{
 const folder=mkdtempSync(join(tmpdir(),'g8-market-browser-')),org={id:'browser-test',name:'Isolated browser test',scopes:['companies:read'],unrestricted:false};
 const db=openTenderDb(join(folder,'server/data/tenders.sqlite'));for(const [email,role]of [['issuer@test.example','issuer'],['bidder@test.example','contributor']])createUser(db,org.id,{name:role==='issuer'?'Test Authority':'Test Supplier',email,password:'BrowserTestPassword123!'},role);db.close();
 const api=createTenderApi(folder,{orgContext:async()=>org,readResource:async()=>({rows:[{id:1,name:'CRM Supplier',description:'Cloud consulting services'}],checkedAt:new Date().toISOString()})});
 const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/tender/')){let raw='';for await(const chunk of req)raw+=chunk;return await api.route(req,res,url,raw?JSON.parse(raw):{});}if(url.pathname.startsWith('/api/')){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(url.pathname==='/api/status'?{configured:false,mode:'Test'}:{rooms:[],experiments:[],goals:[]}));}const file=resolve('dist/graph8-frontend/browser',url.pathname==='/'?'index.html':url.pathname.slice(1));const types={'.js':'application/javascript','.css':'text/css','.html':'text/html'};res.setHeader('Content-Type',types[extname(file)]||'application/octet-stream');res.end(readFileSync(file));}catch(e){res.writeHead(e.status||500,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;let browser;
 try{
 browser=await chromium.launch({channel:'msedge',headless:true,args:['--disable-gpu']});const page=await browser.newPage({viewport:{width:1440,height:1000},timezoneId:'Asia/Karachi'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const signin=async email=>{await page.goto(base+'/#tenders');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('BrowserTestPassword123!');await page.getByRole('button',{name:'Sign in'}).click();await page.getByRole('button',{name:'Sign out',exact:true}).waitFor();};
 await signin('issuer@test.example');await page.getByRole('heading',{name:'Find the right partner.'}).waitFor();assert.equal(await page.getByRole('button',{name:'Supplier profile',exact:true}).count(),0);
 await page.getByRole('button',{name:'Create tender',exact:false}).click();await page.getByLabel('Title',{exact:true}).fill('Browser test cloud tender');await page.getByLabel('Scope, requirements and evaluation criteria').fill('Provide cloud consulting, technical architecture and an evidenced implementation plan.');await page.getByRole('dialog').getByLabel('Country',{exact:true}).fill('Pakistan');await page.getByLabel('Indicative budget').fill('10000');await page.getByLabel(/Closing date and time/).fill('2099-01-01T12:00');await page.getByRole('button',{name:'Save tender draft'}).click();await page.getByRole('button',{name:'Publish tender',exact:true}).click();await page.getByText('Tender published to bidders in this organization',{exact:true}).waitFor();const timezoneDb=openTenderDb(join(folder,'server/data/tenders.sqlite'));try{assert.equal(timezoneDb.list(org.id,'market-tender')[0].deadline,'2099-01-01T07:00:00.000Z');}finally{timezoneDb.close();}await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await signin('bidder@test.example');await page.getByRole('heading',{name:'Find your next opportunity.'}).waitFor();assert.equal(await page.getByRole('button',{name:'Create tender',exact:false}).count(),0);
 await page.getByRole('button',{name:'Supplier profile',exact:true}).click();await page.getByLabel('Company',{exact:true}).fill('Test Supplier');await page.getByLabel('Services and evidenced capabilities').fill('Cloud consulting supported by client delivery references.');await page.getByLabel('Categories (comma separated)').fill('Software & IT');await page.getByRole('button',{name:'Save profile & policy'}).click();await page.getByText('Supplier profile and automation policy saved',{exact:true}).waitFor();
 await page.getByRole('button',{name:'View opportunity',exact:true}).click();await page.getByRole('button',{name:'Prepare a private bid'}).click();await page.getByLabel('Proposal',{exact:true}).fill('We will provide a cloud assessment, architecture review, stakeholder workshops and a detailed implementation roadmap supported by our documented delivery experience.');await page.getByLabel('Offer (USD)').fill('8500');await page.getByLabel('Delivery duration (days)').fill('25');await page.getByLabel('Evidence and capability references').fill('Client reference ABC, delivery plan section 2 and resource schedule.');await page.getByRole('button',{name:'Confirm & submit bid',exact:true}).click();await page.getByText(/Submission receipt:/).waitFor();await page.screenshot({path:'.angular/market-bidder-verified.png',fullPage:true});await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await signin('issuer@test.example');await page.getByRole('button',{name:'Manage & compare bids'}).click();await page.getByRole('cell',{name:'Test Supplier',exact:true}).waitFor();await page.getByRole('button',{name:'Review',exact:true}).click();await page.getByLabel('Technical score / 100').fill('85');await page.getByLabel('Commercial score / 100').fill('90');await page.getByLabel('Evaluation rationale').fill('Meets the documented scope and budget.');await page.getByRole('button',{name:'Save evaluation & shortlist'}).click();await page.getByText('Bid evaluated and shortlisted',{exact:true}).waitFor();await page.screenshot({path:'.angular/market-issuer-verified.png',fullPage:true});
 await page.getByRole('button',{name:'← Back',exact:true}).click();await page.getByRole('heading',{name:'Automatic evaluation summary'}).waitFor();await page.getByText(/leads the recorded evaluation/).waitFor();
 const clockDb=openTenderDb(join(folder,'server/data/tenders.sqlite'));try{const tender=clockDb.list(org.id,'market-tender')[0];clockDb.update(org.id,'market-tender',tender.id,'test','test:deadline',r=>r.deadline=new Date(Date.now()+4000).toISOString());}finally{clockDb.close();}
 await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByRole('button',{name:'Review award',exact:true}).waitFor({timeout:12000});await page.getByRole('button',{name:'Review award',exact:true}).click();await page.getByLabel('Award rationale',{exact:true}).fill('Highest evaluated score against the published scope and confirmed evidence.');await page.getByRole('button',{name:'Confirm award',exact:true}).click();await page.getByText('Awarded to Test Supplier',{exact:false}).waitFor();
 await page.getByRole('button',{name:'Automation & insights',exact:true}).click();const awardedRow=page.locator('.chart-row').filter({has:page.locator('span',{hasText:/^awarded$/})});await awardedRow.locator('b').filter({hasText:/^1$/}).waitFor();
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await signin('bidder@test.example');assert.equal(await page.getByRole('button',{name:'View opportunity',exact:true}).count(),0);await page.getByRole('button',{name:'My bids',exact:true}).click();await page.locator('.card .badge').filter({hasText:/^awarded$/}).waitFor();
 assert.equal(await page.getByRole('alert').count(),0);assert.deepEqual(errors,[]);console.log('Verified distinct roles, blank URL registration, submission receipt and issuer evaluation.');
 }finally{if(browser)await browser.close();api.close();await new Promise(r=>server.close(r));rmSync(folder,{recursive:true,force:true});}
});



